version: '3'
services:
  aria2-pro:
    container_name: aria2_pro
    image: p3terx/aria2-pro
    restart: always
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    environment:
      - LISTEN_PORT=6888
      - RPC_PORT=6800
      - RPC_SECRET=123456
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
      - UMASK_SET=022


    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime
      - /home/bgzo/Downloads/motrix:/downloads

  motrix-web:
    container_name: motrix-web
    image: jarvay/motrix-web
    restart: always
    environment:
      - WEB_UI_PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./motrix-config:/app/config
      # You need to mount the same directory as aria2[-pro], otherwise the function of deleting files will not work
      - /mnt:/downloads