version: "3"
services:
  embyserver:
    image: emby/embyserver:latest
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - ${VIDEOS}/NSFW:/mnt/NSFW Videos
      - ${MUSIC}/NSFW:/mnt/NSFW Music
      - ${VIDEOS}/Bangumi:/mnt/Bangumi
      - ${VIDEOS}/Movie:/mnt/Movie
      - ${VIDEOS}/Series:/mnt/Series
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
      - all_proxy=${PROXY}
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      # - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi

    # runtime: nvidia # Expose NVIDIA GPUs 
      # NOTE: Using environment on NVIDIA_VISIBLE_DEVICES
      # via: https://emby.media/community/index.php?/topic/88165-nvidia-runtime-docker-compose/
    restart: on-failure
