version: "3"
services:
  embyserver:
    image: emby/embyserver:latest
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - ${WORKSPACE}/emby/config:/config
      - ${WORKSPACE}/emby/share1:/mnt/share1
      - ${WORKSPACE}/emby/share2:/mnt/share2