# via: https://github.com/mbentley/docker-timemachine
version: "3.7"
services:
  timemachine:
    image: mbentley/timemachine:smb
    container_name: timemachine
    network_mode: "host"
    environment:
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - PASSWORD=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - SET_PERMISSIONS=false
      - VOLUME_SIZE_LIMIT=0
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - ./data:/opt/timemachine
      - ./smbd.service:/etc/avahi/services/smbd.service
    tmpfs:
      - /run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

