---
version: "2.1"
services:
  nginx:
    image: linuxserver/nginx
    container_name: mb3admin.com #两个容器间互联，实现免改 hosts/DNS 指定 emby 服务端访问本地伪造的 mb3admin.com 网站
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx:/config #nginx 的配置目录，已经部署好伪造证书与 emby 授权的响应
#    ports:
#      - 443:443
#单纯破解与该容器互联的 emby 服务端情况下，无需映射 https 的 443 端口出来
    restart: unless-stopped

  emby:
    image: linuxserver/emby
    depends_on:
      - nginx
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - GIDLIST=985 # grep video /etc/group 
      - TZ=Asia/Shanghai
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      #- http_proxy=${PROXY}
      #- https_proxy=${PROXY}
      #- all_proxy=${PROXY}
    volumes:
      - ./ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt                # 将添加了 伪造CA证书 的信任列表，替换到容器内
      - ./emby-ca-certificates.crt:/app/emby/etc/ssl/certs/ca-certificates.crt  #将添加了 伪造CA证书 的信任列表，替换到容器内（emby 的 c# 环境）
      - ./config:/config                                                        #emby 的配置目录
      - ./thumbnails:/mnt/thumbnails                                            #按需配置媒体目录
      - /dev/dri:/dev/dri                                                       #GPU driver
      - ${VIDEOS}/NSFW:/mnt/NSFW Videos
      - ${MUSIC}/NSFW:/mnt/NSFW Music
      - ${VIDEOS}/Bangumi:/mnt/Bangumi
      - ${VIDEOS}/Movie:/mnt/Movie
      - ${VIDEOS}/Series:/mnt/Series
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      # - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    # runtime: nvidia # Expose NVIDIA GPUs 
      # NOTE: Using environment on NVIDIA_VISIBLE_DEVICES
      # via: https://emby.media/community/index.php?/topic/88165-nvidia-runtime-docker-compose/
    restart: unless-stopped

#其他参数的具体含义，请查阅容器的官方文档
#使用到的 nginx 容器       https://hub.docker.com/r/linuxserver/nginx
#使用到的 emby 容器        https://hub.docker.com/r/linuxserver/emby
