version: "3"
services:
    onedrive:
        image: driveone/onedrive:edge
        restart: unless-stopped
        environment:
            - ONEDRIVE_UID=${PUID}
            - ONEDRIVE_GID=${PGID}
            - http_proxy=${PROXY}
            - https_proxy=${PROXY}
            - all_proxy=${PROXY}
        volumes: 
            - ./conf:/onedrive/conf
            - ./data:/onedrive/data
