version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - ./list:/opt/alist/data
        ports:
            - '5244:5244'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=022
            - http_proxy=${PROXY}
            - https_proxy=${PROXY}
            - all_proxy=${PROXY}
        container_name: alist
        image: 'xhofe/alist:latest'
