# template via https://raw.githubusercontent.com/Suwayomi/docker-tachidesk/refs/heads/main/docker-compose.yml
---
version: '3.7'
services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:preview
    environment:
      - TZ=Etc/UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Comment these out if you do not use the flaresolverr container at the bottom of this file
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://${LAN}:8191
#  #################################################################################################
#
#    !!! IMPORTANT !!!
#     - server settings can be changed during runtime in the WebUI
#     - providing an environment variable will OVERWRITE the current setting value when starting the container
#
#  #################################################################################################
#
#    example for setting env vars:
#
#      - BIND_IP=0.0.0.0
#      - BIND_PORT=4567
      - SOCKS_PROXY_ENABLED=true
      - SOCKS_PROXY_HOST=${PROXY_HOST}
      - SOCKS_PROXY_PORT=${PROXY_PORT}
#      - DOWNLOAD_AS_CBZ=true
#      - BASIC_AUTH_ENABLED=true
#      - BASIC_AUTH_USERNAME=manga
#      - BASIC_AUTH_PASSWORD=hello123
      - EXTENSION_REPOS=["https://github.com/keiyoushi/extensions"]
    volumes:
      - ./data:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4567:4567"
    restart: on-failure:3
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Etc/UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    ports:
      - "8191:8191"
    restart: unless-stopped
